baseURL = "https://mitsuboshi.github.io/blog/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "simple-style"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  "/" = "/:year/:month/:day/:slug/"
