theme = "github-style"
baseURL = "https://mitsuboshi.github.io/blog/"
title = "mitsubosh's blog"
copyright = "© 2020 MITSUBOSHI Yuya"
languageCode = "ja"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true

[params]
  author = "MITSUBOSHI/bosshi"
  description = "MITSUBOSHIのブログです。主に技術や子育てに関する記事を書いています。"
  github = "MITSUBOSHI"
  twitter = "Y_MITSUBOSHI"
  # url = ""
  keywords = "blog, software engineer, child"
  rss = true
  lastmod = true
  favicon = "https://avatars.githubusercontent.com/u/8204936"
  avatar = "https://avatars.githubusercontent.com/u/8204936"
  headerIcon = "https://avatars.githubusercontent.com/u/8204936"
  location = "Kamakura"
  userStatusEmoji = "⚾️"
  enableSearch = true

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "G-SXPHRNPR2H"
