baseURL = "https://mitsuboshi.github.io/blog/"
languageCode = "en-us"
title = "mitsubosh's blog"
theme = "simple-blog"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  "/" = "/:year/:month/:day/:slug/"
