theme = "simple-blog"
baseURL = "https://mitsuboshi.github.io/blog/"
title = "mitsubosh's blog"
copyright = "© 2020 MITSUBOSHI Yuya"
paginate = 3
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true
summaryLength = 100

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  "/" = "/:year/:month/:day/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true